### ISSUE TITLE
RTree fails if requesting just one nearest neighbor

### ISSUE THREAD

**Issue by marceloandrioni** [CNES/pangeo-pyinterp#28]
**Describe the bug**

Hello, I think there is a bug when using RTree to request just one or two nearest neighbors. 

**To Reproduce**

```
import numpy as np
import pyinterp


lon2d, lat2d = np.meshgrid(np.arange(-180, 180, 0.25),
                           np.arange(-90, 90, 0.25),
                           indexing="ij")

lon1d = lon2d.flatten()
lat1d = lat2d.flatten()

data = np.random.rand(*lon2d.shape)
data1d = data.flatten()

# rtree search
mesh = pyinterp.RTree()
mesh.packing(np.column_stack((lon1d, lat1d)), data1d)

lats = [-25, -25.1, -25.12, -25.123]
lons = [-43, -43.9, -43.98, -43.987]

print(f"{pyinterp.__version__=}")
for longitude, latitude in zip(lons, lats):

    print("*" * 30)
    print(latitude, longitude)

    coordinates = np.atleast_2d([longitude, latitude])

    for k in range(4, 0, -1):
        print(k, mesh.query(coordinates, k=k))
```

```
pyinterp.__version__='2024.6.0'
******************************
-25 -43
4 (array([[    0.        , 25237.50255067, 25237.50255067, 27692.73540427]]), array([[0.02426216, 0.51788106, 0.19727041, 0.68730455]]))
3 (array([[    0.        , 25237.50255067, 25237.50255067]]), array([[0.02426216, 0.51788106, 0.19727041]]))
2 (array([[    0.        , 25237.50255067]]), array([[0.02426216, 0.51788106]]))
1 (array([[0.]]), array([[0.02426216]]))
******************************
-25.1 -43.9
4 (array([[14984.4748366 , 18756.80123461, 19435.06184936, 22466.55238439]]), array([[0.73971348, 0.92072835, 0.05436515, 0.4945112 ]]))
3 (array([[14984.4748366 , 18756.80123461, 19435.06184936]]), array([[0.73971348, 0.92072835, 0.05436515]]))
2 (array([[-1., -1.]]), array([[-1., -1.]]))  # fail
1 (array([[-1.]]), array([[-1.]]))  # fail
******************************
-25.12 -43.98
4 (array([[13445.15876146, 14541.25376096, 26744.60868729, 27292.18291444]]), array([[0.73971348, 0.05436515, 0.92072835, 0.4945112 ]]))
3 (array([[13445.15876146, 14541.25376096, 26744.60868729]]), array([[0.73971348, 0.05436515, 0.92072835]]))
2 (array([[13445.15876146, 14541.25376096]]), array([[0.73971348, 0.05436515]]))
1 (array([[-1.]]), array([[-1.]]))  # fail
******************************
-25.123 -43.987
4 (array([[13688.16805791, 14129.40012246, 27522.48596079, 27723.67601241]]), array([[0.73971348, 0.05436515, 0.92072835, 0.4945112 ]]))
3 (array([[13688.16805791, 14129.40012246, 27522.48596079]]), array([[0.73971348, 0.05436515, 0.92072835]]))
2 (array([[13688.16805791, 14129.40012246]]), array([[0.73971348, 0.05436515]]))
1 (array([[-1.]]), array([[-1.]]))   # fail

```

Some searchs fail to return results when requesting just two nearest neighbors (e.g. -25.1, -43.9) and some fail when requesting just a single nearest neighbor (e.g.: -25.123, -43.987).

Of course an user can just request 4 nearest neighbors and select just the first one if desired, but I thought RTree behavior was a little odd and decided to report it.

Thank you.

**Comment by fbriol** [comment]
This library and its RTree object use a default behavior to handle interpolation. The method you’re using includes a keyword, ``within,`` which alters this default behavior.

The ``within`` option tells the search method to ensure that the requested point is surrounded by the found points before performing the interpolation. This prevents the algorithm from using points outside the relevant area for interpolation, effectively avoiding extrapolation.

When you request points on a grid, the found points will always be enclosed by at least one grid point because the points coincide with the grid structure.

For example, the figure below illustrates your query when you request two points for a point on the grid. The line represents the segment connecting the two closest grid points, and the orange circle is the query point. Since the point lies between two grid points on this segment, the query works.

![ex_2](https://github.com/user-attachments/assets/9c89ac21-e5d0-4be0-a1e5-5c4d6ae7403a)

However, if you slightly shift the coordinates of your point relative to the grid, the behavior changes. For 4 points, the query works because the surrounding points form a triangle or quadrilateral that encloses the query point. The same applies to 3 points. But when querying for only 2 points, unless the query point is located exactly on the segment between two grid points, the query will fail, as the point is no longer enclosed by the found points.

![output](https://github.com/user-attachments/assets/400a291d-1f79-4066-9d6d-2c19910ac2e5)
![output2](https://github.com/user-attachments/assets/a70da224-c3a8-4e26-96e6-f4fde8a830b1)

If you want to override this behavior and allow interpolation (even when the point isn’t enclosed by the grid points), you need to set the ``within`` keyword to false.

**Comment by marceloandrioni** [comment]
Hello @fbriol, thank you for the great explanation with images. I will use the `within=False` then to just the single nearest point. Thank you.
